name: Giannis daap CICD
on:
  push:
    branches:
      - 'main'

env:
  DBT_PROFILES_DIR: .
  DBT_USER: ${{ secrets.DBT_PROD_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
  DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
  DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
  DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}
  DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}


jobs:
  pre-commit:
    name: Run pre-commit checks 🔬
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          architecture: x64
      - name: Install dependencies
        run: make dev-deps
      - name: Run pre-commit
        run: make pre-commit args="--all-files"

  semver-release:
    runs-on: ubuntu-latest
    needs:
      - pre-commit
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Release
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release