-- Change all SAMPLE_DAAP with your resources.

USE ROLE R_SAMPLE_DAAP_MASTER;
-- CREATE A STAGE IN YOUR RAW SCHEMA
SHOW INTEGRATIONS;
DESCRIBE INTEGRATION "stg_generic-27b70f5";

CREATE OR REPLACE STAGE DB_DATA_PRODUCTS.SAMPLE_DAAP_RAW.SAMPLE_STAGE
STORAGE_INTEGRATION = "stg_generic-27b70f5"
url = 's3://orfium-data-de-dev/workshop_daap_in_snowflake/tpch_sf10/';


-- DATA LOADING INTO EXISTING TABLE
USE ROLE R_SAMPLE_DAAP_MASTER;
CREATE or REPLACE TRANSIENT TABLE DB_DATA_PRODUCTS.SAMPLE_DAAP_RAW.LINEITEM (
	L_ORDERKEY NUMBER(38,0),
	L_PARTKEY NUMBER(38,0),
	L_SUPPKEY NUMBER(38,0),
	L_LINENUMBER NUMBER(38,0),
	L_QUANTITY NUMBER(12,2),
	L_EXTENDEDPRICE NUMBER(12,2),
	L_DISCOUNT NUMBER(12,2),
	L_TAX NUMBER(12,2),
	L_RETURNFLAG VARCHAR(1),
	L_LINESTATUS VARCHAR(1),
	L_SHIPDATE DATE,
	L_COMMITDATE DATE,
	L_RECEIPTDATE DATE,
	L_SHIPINSTRUCT VARCHAR(25),
	L_SHIPMODE VARCHAR(10),
	L_COMMENT VARCHAR(44)
);

COPY INTO DB_DATA_PRODUCTS.SAMPLE_DAAP_RAW.LINEITEM
FROM @DB_DATA_PRODUCTS.SAMPLE_DAAP_RAW.SAMPLE_STAGE/lineitem_10000.csv.gz
FILE_FORMAT= (type='csv', skip_header=1);

--  CREATING EXTERNAL TABLE

CREATE OR REPLACE EXTERNAL TABLE DB_DATA_PRODUCTS.SAMPLE_DAAP_RAW.ORDERS
LOCATION=@DB_DATA_PRODUCTS.SAMPLE_DAAP_RAW.SAMPLE_STAGE
PATTERN = '.*orders.*'
FILE_FORMAT = (type='csv', skip_header=1)
AUTO_REFRESH = true;


select value as json_value from DB_DATA_PRODUCTS.SAMPLE_DAAP_RAW.ORDERS limit 10;
