
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'giannis_daap'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake_giannis_daap'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]
model-paths: ["models"]
docs-paths: ["docs"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
# These settings can be overridden in the individual model files
models:
  +materialized: view
  +transient:  "{{ true if env_var('DBT_TEST_ENV','No') == 'Yes' else false }}" 
  +persist_docs:
    relation: true
    columns: true
  giannis_daap:
    giannis_daap:
      +schema: giannis_daap

seeds:
  +quote_columns: false
  +schema: giannis_daap_raw


vars:
  payment_methods: ["bank_transfer", "credit_card", "coupon", "gift_card"]
