USE ROLE SECURITYADMIN;
-- GRANT ACCESS TO WAREHOUSE
GRANT OWNERSHIP ON WAREHOUSE WH_SAMPLE TO ROLE R_SAMPLE_MASTER;
GRANT OPERATE, USAGE ON WAREHOUSE WH_SAMPLE TO ROLE R_SAMPLE_RO;

-- GRANT ACCESS TO DATABASE
GRANT MONITOR, USAGE ON DATABASE DB_DATA_PRODUCTS TO ROLE R_SAMPLE_RO;

-- GRANT ACCESS TO INTEGRATIONS
GRANT USAGE ON INTEGRATION STG_GENERIC_WORKSHOP TO ROLE R_SAMPLE_MASTER;

-- GRANT ACCESS TO SCHEMAS
GRANT
	CREATE TABLE,
    CREATE EXTERNAL TABLE,
    CREATE VIEW,
    CREATE MATERIALIZED VIEW,
    CREATE MASKING POLICY,
    CREATE ROW ACCESS POLICY,
    CREATE SESSION POLICY,
    CREATE STAGE,
    CREATE FILE FORMAT,
    CREATE SEQUENCE,
    CREATE FUNCTION,
    CREATE PIPE,
    CREATE STREAM,
    CREATE TAG,
    CREATE TASK,
    CREATE PROCEDURE
ON SCHEMA DB_DATA_PRODUCTS.SAMPLE TO ROLE R_SAMPLE_MASTER;
GRANT USAGE, MONITOR ON SCHEMA DB_DATA_PRODUCTS.SAMPLE TO R_SAMPLE_RO;

-- GRANT ACCESS TO TABLES

GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA DB_DATA_PRODUCTS.SAMPLE TO ROLE R_SAMPLE_MASTER;
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA DB_DATA_PRODUCTS.SAMPLE TO ROLE R_SAMPLE_RO;

GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA DB_DATA_PRODUCTS.SAMPLE TO ROLE R_SAMPLE_MASTER;
GRANT SELECT, REFERENCES ON FUTURE TABLES IN SCHEMA DB_DATA_PRODUCTS.SAMPLE TO ROLE R_SAMPLE_RO;

-- GRANT ACCESS TO VIEWS
GRANT SELECT, REFERENCES ON ALL VIEWS IN SCHEMA DB_DATA_PRODUCTS.SAMPLE TO ROLE R_SAMPLE_RO;

GRANT SELECT, REFERENCES ON FUTURE VIEWS IN SCHEMA DB_DATA_PRODUCTS.SAMPLE TO ROLE R_SAMPLE_RO;

-- GRANT ACCESS TO EXTERNAL TABLES
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL EXTERNAL TABLES IN SCHEMA DB_DATA_PRODUCTS.SAMPLE TO ROLE R_SAMPLE_MASTER;
GRANT SELECT, REFERENCES ON ALL EXTERNAL TABLES IN SCHEMA DB_DATA_PRODUCTS.SAMPLE TO ROLE R_SAMPLE_RO;

GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE EXTERNAL TABLES IN SCHEMA DB_DATA_PRODUCTS.SAMPLE TO ROLE R_SAMPLE_MASTER;
GRANT SELECT, REFERENCES ON FUTURE EXTERNAL TABLES IN SCHEMA DB_DATA_PRODUCTS.SAMPLE TO ROLE R_SAMPLE_RO;