USE ROLE SECURITYADMIN;
-- CREATE ROLES
CREATE ROLE R_SAMPLE_MASTER;
CREATE ROLE R_SAMPLE_RO;

-- ROLE HIERARCHY
GRANT ROLE R_SAMPLE_MASTER TO ROLE SYSADMIN;
GRANT ROLE R_SAMPLE_RO TO ROLE R_SAMPLE_MASTER;

-- GRANT ROLE TO YOURT USER
GRANT ROLE R_SAMPLE_MASTER TO USER U_SAMPLE;

USE ROLE SYSADMIN;
-- CREATE WAREHOUSE
CREATE WAREHOUSE IF NOT EXISTS WH_SAMPLE
WAREHOUSE_SIZE=XSMALL
INITIALLY_SUSPENDED=TRUE
AUTO_SUSPEND=10400;

-- CREATE SCHEMA
CREATE SCHEMA IF NOT EXISTS DB_DATA_PRODUCTS.SAMPLE
WITH MANAGED ACCESS
MAX_DATA_EXTENSION_TIME_IN_DAYS = 1;